spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/servicefinder
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080